// web/frpc/src/views/VisitorList.vue
<template>
  <n-space vertical :size="16">
    <n-space justify="space-between" align="center" :wrap="false">
      <n-text strong style="font-size: 28px;">访问器列表</n-text>

      <n-button v-if="visitorStore.storeEnabled" type="primary" size="small" @click="handleCreate">
        + 新建访问器
      </n-button>
    </n-space>

    <n-card :bordered="false">
      <n-space vertical :size="16">
        <template v-if="visitorStore.storeEnabled">
          <n-grid responsive="screen" cols="1 m:2" :x-gap="12" :y-gap="12">
            <n-gi>
              <n-input v-model:value="searchText" placeholder="搜索访问器名称" clearable>
                <template #prefix><n-icon><Search /></n-icon></template>
              </n-input>
            </n-gi>
            <n-gi>
              <n-select v-model:value="typeFilter" :options="typeFilterOptions" />
            </n-gi>
          </n-grid>
        </template>
      </n-space>
    </n-card>

    <n-spin :show="visitorStore.loading">
      <n-card v-if="!visitorStore.storeEnabled" size="small" title="本地持久化配置未启用">
        <n-space vertical :size="12">
          <n-text depth="3">请在 frpc 配置中加入以下内容：</n-text>
          <n-card size="small" embedded>
            <pre v-text="configText"></pre>
          </n-card>
        </n-space>
      </n-card>

      <template v-else>
        <n-space v-if="filteredVisitors.length > 0" vertical :size="12">
          <n-card v-for="v in filteredVisitors" :key="v.name" size="small" hoverable @click="goToDetail(v.name)">
            <template #header>
              <n-space align="center" :size="8">
                <span :style="{ fontWeight: 600 }">{{ v.name }}</span>
                <n-tag size="small" :bordered="false">{{ v.type.toUpperCase() }}</n-tag>
              </n-space>
            </template>
            <template #header-extra>
              <n-dropdown trigger="click" placement="bottom-end" :options="visitorActionOptions"
                @select="(key) => handleVisitorAction(key, v)">
                <n-button type="primary" secondary quaternary size="small" @click.stop>
                  <template #icon>
                    <n-icon><Dots /></n-icon>
                  </template>
                </n-button>
              </n-dropdown>
            </template>

            <n-text depth="3">{{ getServerName(v) || '未设置服务端代理' }}</n-text>
          </n-card>
        </n-space>
        <n-empty v-else description="暂无访问器" style="min-height: 50vh; display: flex; flex-direction: column; align-items: center; justify-content: center;"/>
      </template>
    </n-spin>

    <n-modal v-model:show="deleteDialog.visible" preset="card" title="删除访问器"
      :style="{ width: isMobile ? 'calc(100vw - 24px)' : '400px' }" :mask-closable="false">
      <n-text depth="3">{{ deleteDialog.message }}</n-text>
      <template #footer>
        <n-space justify="end">
          <n-button type="primary" secondary quaternary @click="deleteDialog.visible = false">
            取消
          </n-button>
          <n-button type="error" :loading="deleteDialog.loading" @click="doDelete">
            删除
          </n-button>
        </n-space>
      </template>
    </n-modal>
  </n-space>
</template>

<script setup lang="ts">
import { ref, computed, reactive, onMounted, h } from 'vue'
import { useRouter } from 'vue-router'
import { NButton, NCard, NDropdown, NEmpty, NGrid, NGi, NIcon, NInput, NModal, NSelect, NSpin, NSpace, NTag, NText } from 'naive-ui'
import { Dots, Edit, Search, Trash } from '@vicons/tabler'
import { useVisitorStore } from '../stores/visitor'
import { useResponsive } from '../composables/useResponsive'
import type { VisitorDefinition } from '../types'
import { createMessageHelpers } from '../naive'

const { isMobile } = useResponsive()
const router = useRouter()
const visitorStore = useVisitorStore()
const message = createMessageHelpers()

const searchText = ref('')
const typeFilter = ref('')

const configText = `[store]\npath = "./frpc_store.json"`;

const deleteDialog = reactive({
  visible: false,
  message: '',
  loading: false,
  name: '',
})

const typeOptions = computed(() => {
  return [
    { label: 'STCP', value: 'stcp' },
    { label: 'SUDP', value: 'sudp' },
    { label: 'XTCP', value: 'xtcp' },
  ]
})

const typeFilterOptions = computed(() => [
  { label: '全部类型', value: '' },
  ...typeOptions.value,
])

const renderActionIcon = (icon: any) => () =>
  h(NIcon, null, { default: () => h(icon) })

const visitorActionOptions = [
  { label: '编辑', key: 'edit', icon: renderActionIcon(Edit) },
  {
    label: '删除',
    key: 'delete',
    icon: renderActionIcon(Trash),
  },
]

const filteredVisitors = computed(() => {
  let list = visitorStore.storeVisitors

  if (typeFilter.value) {
    list = list.filter((v) => v.type === typeFilter.value)
  }

  if (searchText.value) {
    const q = searchText.value.toLowerCase()
    list = list.filter((v) => v.name.toLowerCase().includes(q))
  }

  return list
})

const getServerName = (v: VisitorDefinition): string => {
  const block = (v as any)[v.type]
  return block?.serverName || ''
}

const fetchData = () => {
  visitorStore.fetchStoreVisitors()
}

const handleCreate = () => {
  router.push('/visitors/create')
}

const handleEdit = (v: VisitorDefinition) => {
  router.push('/visitors/' + encodeURIComponent(v.name) + '/edit')
}

const goToDetail = (name: string) => {
  router.push('/visitors/detail/' + encodeURIComponent(name))
}

const handleDelete = (name: string) => {
  deleteDialog.name = name
  deleteDialog.message = `确认删除访问器“${name}”吗？删除后无法恢复。`
  deleteDialog.visible = true
}

const handleVisitorAction = (key: string | number, visitor: VisitorDefinition) => {
  if (key === 'edit') {
    handleEdit(visitor)
  } else if (key === 'delete') {
    handleDelete(visitor.name)
  }
}

const doDelete = async () => {
  deleteDialog.loading = true
  try {
    await visitorStore.deleteVisitor(deleteDialog.name)
    message.success('访问器已删除')
    deleteDialog.visible = false
    fetchData()
  } catch (err: any) {
    message.error('删除失败：' + (err.message || '未知错误'))
  } finally {
    deleteDialog.loading = false
  }
}

onMounted(() => {
  fetchData()
})
</script>

// web/frpc/src/views/VisitorList.tsx
import { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router'
import {
  MoreHorizontalIcon,
  PencilIcon,
  PlusIcon,
  Search,
  Trash2Icon,
} from 'lucide-react'
import { toast } from 'sonner'

import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu'
import {
  InputGroup,
  InputGroupAddon,
  InputGroupInput,
} from '@/components/ui/input-group'
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import {
  EmptyState,
  LoadingState,
  PageHeader,
  PageSection,
} from '@common/components/Page'
import { useVisitorStore } from '../stores/visitor'
import type { VisitorDefinition } from '../types'

const configText = `[store]\npath = "./frpc_store.json"`

export default function VisitorList() {
  const navigate = useNavigate()
  const visitorStore = useVisitorStore()
  const [searchText, setSearchText] = useState('')
  const [typeFilter, setTypeFilter] = useState('')
  const [deleteName, setDeleteName] = useState('')

  useEffect(() => {
    visitorStore.fetchStoreVisitors()
  }, [])

  const typeOptions = useMemo(
    () =>
      Array.from(new Set(visitorStore.visitors.map((visitor) => visitor.type))),
    [visitorStore.visitors],
  )
  const filteredVisitors = useMemo(() => {
    let result = visitorStore.visitors
    if (typeFilter)
      result = result.filter((visitor) => visitor.type === typeFilter)
    if (searchText) {
      const q = searchText.toLowerCase()
      result = result.filter((visitor) =>
        visitor.name.toLowerCase().includes(q),
      )
    }
    return result
  }, [searchText, typeFilter, visitorStore.visitors])

  const doDelete = async () => {
    try {
      await visitorStore.deleteVisitor(deleteName)
      toast.success('访问器已删除')
      setDeleteName('')
    } catch (err: any) {
      toast.error('删除失败：' + (err.message || '未知错误'))
    }
  }

  return (
    <PageSection>
      <PageHeader
        title="访问器列表"
        actions={
          visitorStore.storeEnabled ? (
            <Button onClick={() => navigate('/visitors/create')}>
              <PlusIcon data-icon="inline-start" />
              新建访问器
            </Button>
          ) : null
        }
      />
      <div className="grid gap-3 md:grid-cols-2">
        <InputGroup>
          <InputGroupInput
            value={searchText}
            onChange={(event) => setSearchText(event.target.value)}
            placeholder="搜索访问器名称"
          />
          <InputGroupAddon>
            <Search />
          </InputGroupAddon>
          <InputGroupAddon align="inline-end" className="hidden md:flex">
            {filteredVisitors.length} 项
          </InputGroupAddon>
        </InputGroup>
        <Select
          value={typeFilter || 'all'}
          onValueChange={(value) => setTypeFilter(value === 'all' ? '' : value)}
        >
          <SelectTrigger className="w-full">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectGroup>
              <SelectItem value="all">全部类型</SelectItem>
              {typeOptions.map((item) => (
                <SelectItem key={item} value={item}>
                  {item.toUpperCase()}
                </SelectItem>
              ))}
            </SelectGroup>
          </SelectContent>
        </Select>
      </div>

      {visitorStore.loading ? (
        <LoadingState />
      ) : !visitorStore.storeEnabled ? (
        <Card>
          <CardHeader>
            <CardTitle>本地持久化配置未启用</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-muted-foreground">
              请在 frpc 配置中加入以下内容：
            </p>
            <pre className="mt-3 overflow-auto text-sm font-mono">
              {configText}
            </pre>
          </CardContent>
        </Card>
      ) : filteredVisitors.length > 0 ? (
        <div className="flex flex-col gap-3">
          {filteredVisitors.map((visitor) => (
            <VisitorCard
              key={visitor.name}
              visitor={visitor}
              onClick={() =>
                navigate(`/visitors/detail/${encodeURIComponent(visitor.name)}`)
              }
              onEdit={() =>
                navigate(`/visitors/${encodeURIComponent(visitor.name)}/edit`)
              }
              onDelete={() => setDeleteName(visitor.name)}
            />
          ))}
        </div>
      ) : (
        <EmptyState title="暂无访问器" />
      )}

      <AlertDialog
        open={!!deleteName}
        onOpenChange={(open) => !open && setDeleteName('')}
      >
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>删除访问器</AlertDialogTitle>
            <AlertDialogDescription>
              确认删除访问器“{deleteName}”吗？删除后无法恢复。
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>取消</AlertDialogCancel>
            <AlertDialogAction onClick={doDelete}>删除</AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </PageSection>
  )
}

function VisitorCard({
  visitor,
  onClick,
  onEdit,
  onDelete,
}: {
  visitor: VisitorDefinition
  onClick: () => void
  onEdit: () => void
  onDelete: () => void
}) {
  const block = (visitor as any)[visitor.type] || {}
  const serverName = block.serverName || ''
  const enabled = block.enabled !== false

  return (
    <Card>
      <CardHeader>
        <div className="flex items-start justify-between gap-3">
          <button className="min-w-0 text-left" onClick={onClick}>
            <CardTitle className="flex flex-wrap items-center gap-2 text-base">
              {visitor.name}
              <Badge variant="secondary">{visitor.type.toUpperCase()}</Badge>
              <Badge variant={enabled ? 'default' : 'secondary'}>
                {enabled ? '启用' : '禁用'}
              </Badge>
            </CardTitle>
          </button>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="ghost" size="icon">
                <MoreHorizontalIcon />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuGroup>
                <DropdownMenuItem onSelect={onEdit}>
                  <PencilIcon />
                  编辑
                </DropdownMenuItem>
                <DropdownMenuItem variant="destructive" onSelect={onDelete}>
                  <Trash2Icon />
                  删除
                </DropdownMenuItem>
              </DropdownMenuGroup>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </CardHeader>
      <CardContent>
        <button
          className="w-full text-left text-sm text-muted-foreground"
          onClick={onClick}
        >
          {serverName || '未设置服务端代理'}
        </button>
      </CardContent>
    </Card>
  )
}
