// web/common/components/DashboardConfigEditor.vue
<template>
  <n-space vertical>
    <n-space justify="space-between" align="center" wrap>
      <n-text style="font-size: 24px;" strong>{{ title }}</n-text>

      <n-space align="center" :size="12">
        <n-button v-if="docUrl" text tag="a" :href="docUrl" target="_blank" rel="noreferrer">
          {{ docLabel }}
        </n-button>

        <n-button v-if="showRefresh" secondary :loading="loading" @click="fetchConfig"> 
          {{ refreshLabel }}
        </n-button>

        <n-button type="primary" :loading="saving" @click="handleSave">
          {{ saveLabel }}
        </n-button>
      </n-space>
    </n-space>

    <n-card :bordered="false" size="small" segmented>
      <template #header>
        <n-text strong>{{ cardTitle }}</n-text>
      </template>

      <n-input v-model:value="content" type="textarea" :autosize="{ minRows: textareaMinRows }"
        :placeholder="placeholder" />
    </n-card>
  </n-space>
</template>

<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { NButton, NCard, NInput, NSpace, NText, useDialog, useMessage } from 'naive-ui'

const props = withDefaults(
  defineProps<{
    title: string
    cardTitle: string
    headerHint?: string
    placeholder: string
    saveLabel: string
    refreshLabel?: string
    docLabel?: string
    docUrl?: string
    showRefresh?: boolean
    confirmTitle?: string
    confirmContent?: string
    textareaMinRows?: number
    loadConfig: () => Promise<string>
    saveConfig: (content: string) => Promise<{ message?: string } | void>
    afterSave?: () => Promise<void> | void
    loadErrorPrefix?: string
    saveErrorPrefix?: string
    successMessage?: string
    emptyMessage?: string
  }>(),
  {
    refreshLabel: '刷新',
    docLabel: '查看配置文档',
    showRefresh: false,
    confirmTitle: '',
    confirmContent: '',
    textareaMinRows: 24,
    afterSave: undefined,
    loadErrorPrefix: '获取配置失败: ',
    saveErrorPrefix: '保存配置失败: ',
    successMessage: '配置已保存',
    emptyMessage: '配置内容不能为空',
  },
)

const dialog = useDialog()
const message = useMessage()
const content = ref('')
const loading = ref(false)
const saving = ref(false)

const fetchConfig = async () => {
  loading.value = true
  try {
    content.value = await props.loadConfig()
  } catch (err: any) {
    message.error(props.loadErrorPrefix + (err?.message || '未知错误'))
  } finally {
    loading.value = false
  }
}

const doSave = async () => {
  if (!content.value.trim()) {
    message.warning(props.emptyMessage)
    return
  }

  saving.value = true
  try {
    const result = await props.saveConfig(content.value)
    await props.afterSave?.()
    message.success(result?.message || props.successMessage)
  } catch (err: any) {
    message.error(props.saveErrorPrefix + (err?.message || '未知错误'))
  } finally {
    saving.value = false
  }
}

const handleSave = () => {
  if (props.confirmTitle || props.confirmContent) {
    dialog.warning({
      title: props.confirmTitle || props.saveLabel,
      content: props.confirmContent,
      positiveText: '确认',
      negativeText: '取消',
      onPositiveClick: doSave,
    })
    return
  }

  void doSave()
}

onMounted(fetchConfig)
</script>

<style scoped>
</style>

// web/common/components/DashboardConfigEditor.tsx
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { ExternalLinkIcon, RefreshCwIcon, SaveIcon } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Spinner } from "@/components/ui/spinner";

interface DashboardConfigEditorProps {
  title: string;
  cardTitle: string;
  docUrl?: string;
  textareaMinRows?: number;
  showRefresh?: boolean;
  fetchConfig: () => Promise<string>;
  saveConfig: (content: string) => Promise<void>;
  reloadConfig?: () => Promise<void>;
}

export function DashboardConfigEditor({
  title,
  cardTitle,
  docUrl,
  textareaMinRows = 18,
  showRefresh = true,
  fetchConfig,
  saveConfig,
  reloadConfig,
}: DashboardConfigEditorProps) {
  const [content, setContent] = useState("");
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);

  const loadConfig = async () => {
    setLoading(true);
    try {
      setContent(await fetchConfig());
    } catch (err: any) {
      toast.error("获取配置失败：" + (err.message || "未知错误"));
    } finally {
      setLoading(false);
    }
  };

  const handleSave = async () => {
    setSaving(true);
    try {
      await saveConfig(content);
      if (reloadConfig) {
        await reloadConfig();
      }
      toast.success("配置已保存");
    } catch (err: any) {
      toast.error("保存配置失败：" + (err.message || "未知错误"));
    } finally {
      setSaving(false);
    }
  };

  useEffect(() => {
    loadConfig();
  }, []);

  return (
    <div className="flex flex-col gap-4">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <h1 className="text-2xl font-semibold">{title}</h1>
        <div className="flex items-center gap-2">
          {docUrl ? (
            <Button variant="ghost" asChild>
              <a href={docUrl} target="_blank" rel="noreferrer">
                <ExternalLinkIcon data-icon="inline-start" />
                文档
              </a>
            </Button>
          ) : null}
          {showRefresh ? (
            <Button variant="outline" onClick={loadConfig} disabled={loading}>
              {loading ? (
                <Spinner data-icon="inline-start" />
              ) : (
                <RefreshCwIcon data-icon="inline-start" />
              )}
              刷新
            </Button>
          ) : null}
          <Button onClick={handleSave} disabled={saving}>
            {saving ? (
              <Spinner data-icon="inline-start" />
            ) : (
              <SaveIcon data-icon="inline-start" />
            )}
            保存
          </Button>
        </div>
      </div>
      {cardTitle}
      <Textarea
        value={content}
        onChange={(event) => setContent(event.target.value)}
        style={{ minHeight: `${textareaMinRows * 1.5}rem` }}
        className="font-mono"
      />
    </div>
  );
}
